package org.cdms.auth;

import java.util.prefs.Preferences;
import org.openide.util.NbPreferences;

/**
 * Allows a user to authenticate.
 * @author V. Shyshkin
 */
public class LoginPane extends javax.swing.JPanel {

    /**
     * Creates new form LoginPane
     */
    public LoginPane() {
        initComponents();
    }
    
    public String getHttpAddress() {
        return this.jTextField1_IP_Address.getText();
    }
    public String getHttpPort() {
        return this.jTextField1_Port.getText();
    }
    public void setHttpAddress(String ip) {
        this.jTextField1_IP_Address.setText(ip);
    }
    public void setHttpPort(String port) {
        this.jTextField1_Port.setText(port);
    }
    
   public String getUsername() {
      return jTextField_UserName.getText().toUpperCase();
   }
   
   public String getPassword() {
      return new String(jPasswordField_Password.getPassword());
   }
   
   public void setLoginMsg(String msg) {
      jLabel_message.setText(msg);
   }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_UserName = new javax.swing.JLabel();
        jTextField_UserName = new javax.swing.JTextField();
        jLabel_Psw = new javax.swing.JLabel();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jLabel_message = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1_IP_Address = new javax.swing.JLabel();
        jLabel1_Port = new javax.swing.JLabel();
        jTextField1_IP_Address = new javax.swing.JTextField();
        jTextField1_Port = new javax.swing.JTextField();
        jButton1_save = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\VnsJob\\cdms-client\\cdms-auth\\src\\org\\cdms\\auth\\icon_login.png")); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(LoginPane.class, "LoginPane.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel_UserName, org.openide.util.NbBundle.getMessage(LoginPane.class, "LoginPane.jLabel_UserName.text")); // NOI18N

        jTextField_UserName.setColumns(16);
        jTextField_UserName.setText(org.openide.util.NbBundle.getMessage(LoginPane.class, "LoginPane.jTextField_UserName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel_Psw, org.openide.util.NbBundle.getMessage(LoginPane.class, "LoginPane.jLabel_Psw.text")); // NOI18N

        jPasswordField_Password.setColumns(16);
        jPasswordField_Password.setText(org.openide.util.NbBundle.getMessage(LoginPane.class, "LoginPane.jPasswordField_Password.text")); // NOI18N

        jLabel_message.setForeground(new java.awt.Color(255, 51, 0));
        jLabel_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel_message, org.openide.util.NbBundle.getMessage(LoginPane.class, "LoginPane.jLabel_message.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Psw))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Psw)
                            .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_message, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(LoginPane.class, "LoginPane.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1_IP_Address, org.openide.util.NbBundle.getMessage(LoginPane.class, "LoginPane.jLabel1_IP_Address.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1_Port, org.openide.util.NbBundle.getMessage(LoginPane.class, "LoginPane.jLabel1_Port.text")); // NOI18N

        jTextField1_IP_Address.setText(org.openide.util.NbBundle.getMessage(LoginPane.class, "LoginPane.jTextField1_IP_Address.text")); // NOI18N

        jTextField1_Port.setText(org.openide.util.NbBundle.getMessage(LoginPane.class, "LoginPane.jTextField1_Port.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1_save, org.openide.util.NbBundle.getMessage(LoginPane.class, "LoginPane.jButton1_save.text")); // NOI18N
        jButton1_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1_Port, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField1_Port, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1_IP_Address)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1_save)
                            .addComponent(jTextField1_IP_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_IP_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_IP_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_Port)
                    .addComponent(jTextField1_Port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jButton1_save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(LoginPane.class, "LoginPane.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_saveActionPerformed
        Preferences node = NbPreferences.root();
        String sn = getHttpAddress();
        node.put("server.name", getHttpAddress());
        try {
            node.putInt("server.port", Integer.parseInt(getHttpPort()));    
        } catch(Exception e) {
            
        }
        

    }//GEN-LAST:event_jButton1_saveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_IP_Address;
    private javax.swing.JLabel jLabel1_Port;
    private javax.swing.JLabel jLabel_Psw;
    private javax.swing.JLabel jLabel_UserName;
    private javax.swing.JLabel jLabel_message;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1_IP_Address;
    private javax.swing.JTextField jTextField1_Port;
    private javax.swing.JTextField jTextField_UserName;
    // End of variables declaration//GEN-END:variables
}
