/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cdms.ui.common.dialog;

import org.cdms.remoting.exception.RemoteDataAccessException;

/**
 *
 * @author Valery
 */
public class ErrorDataAccesDetailsPane extends javax.swing.JPanel {
    private RemoteDataAccessException exception;
    /**
     * Creates new form ErrorDataAccesDetailsPane
     */
    public ErrorDataAccesDetailsPane() {
        initComponents();
    }
    
    public RemoteDataAccessException getExeption() {
        return exception;
    }

    public void setException(RemoteDataAccessException exeption) {
        this.exception = exeption;
        if ( exception == null ) {
            return;
        }
        String identifier = exception.getIdentifier() != null ? exception.getIdentifier().toString() : "";
        jLabel_Identifier.setText(identifier);
        jLabel_EntityName.setText(exception.getEntityName());
        jLabel_EntityClass.setText(exception.getPersistentClassName());
        jLabel_ExceptionClass.setText(exception.getOriginalClassName());
        jLabel_Message.setText("<html>" + exception.getMessage()+"</html>"); //html for word wrapping
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Identifier_cap = new javax.swing.JLabel();
        jLabel_Identifier = new javax.swing.JLabel();
        jLabel_EntityName_cap = new javax.swing.JLabel();
        jLabel_EntityName = new javax.swing.JLabel();
        jLabel_EntityClass_cap = new javax.swing.JLabel();
        jLabel_EntityClass = new javax.swing.JLabel();
        jLabel_ExceptionClass_cap = new javax.swing.JLabel();
        jLabel_ExceptionClass = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Message = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel_Identifier_cap, org.openide.util.NbBundle.getMessage(ErrorDataAccesDetailsPane.class, "ErrorDataAccesDetailsPane.jLabel_Identifier_cap.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel_Identifier, org.openide.util.NbBundle.getMessage(ErrorDataAccesDetailsPane.class, "ErrorDataAccesDetailsPane.jLabel_Identifier.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel_EntityName_cap, org.openide.util.NbBundle.getMessage(ErrorDataAccesDetailsPane.class, "ErrorDataAccesDetailsPane.jLabel_EntityName_cap.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel_EntityName, org.openide.util.NbBundle.getMessage(ErrorDataAccesDetailsPane.class, "ErrorDataAccesDetailsPane.jLabel_EntityName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel_EntityClass_cap, org.openide.util.NbBundle.getMessage(ErrorDataAccesDetailsPane.class, "ErrorDataAccesDetailsPane.jLabel_EntityClass_cap.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel_EntityClass, org.openide.util.NbBundle.getMessage(ErrorDataAccesDetailsPane.class, "ErrorDataAccesDetailsPane.jLabel_EntityClass.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel_ExceptionClass_cap, org.openide.util.NbBundle.getMessage(ErrorDataAccesDetailsPane.class, "ErrorDataAccesDetailsPane.jLabel_ExceptionClass_cap.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel_ExceptionClass, org.openide.util.NbBundle.getMessage(ErrorDataAccesDetailsPane.class, "ErrorDataAccesDetailsPane.jLabel_ExceptionClass.text")); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ErrorDataAccesDetailsPane.class, "ErrorDataAccesDetailsPane.jPanel2.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel_Message, org.openide.util.NbBundle.getMessage(ErrorDataAccesDetailsPane.class, "ErrorDataAccesDetailsPane.jLabel_Message.text")); // NOI18N
        jLabel_Message.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel_Message.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Message, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Message, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Identifier_cap)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel_Identifier))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_EntityClass_cap)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel_EntityClass))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_ExceptionClass_cap)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel_ExceptionClass))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_EntityName_cap)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel_EntityName)))
                        .addGap(0, 240, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Identifier_cap)
                    .addComponent(jLabel_Identifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntityName_cap)
                    .addComponent(jLabel_EntityName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntityClass_cap)
                    .addComponent(jLabel_EntityClass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ExceptionClass)
                    .addComponent(jLabel_ExceptionClass_cap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel jLabel_EntityClass;
    private javax.swing.JLabel jLabel_EntityClass_cap;
    protected javax.swing.JLabel jLabel_EntityName;
    private javax.swing.JLabel jLabel_EntityName_cap;
    protected javax.swing.JLabel jLabel_ExceptionClass;
    private javax.swing.JLabel jLabel_ExceptionClass_cap;
    protected javax.swing.JLabel jLabel_Identifier;
    private javax.swing.JLabel jLabel_Identifier_cap;
    protected javax.swing.JLabel jLabel_Message;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
