/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vns.comp;

import com.qt.datapicker.DatePicker;
import java.text.DateFormat;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author Valery
 */
public class DatePickerEx extends javax.swing.JPanel {
    private DatePicker datePicker;
    
    //private DateTextField dateField;
    /**
     * Creates new form DatePickerEx
     */
    public DatePickerEx() {
        initComponents();
        initDateFields();
        
    }
    protected final void initDateFields() {
        datePicker = new DatePicker(dateField);
        dateField.setHorizontalAlignment(JTextField.CENTER);
        dateField.setFormatterFactory(
                new DefaultFormatterFactory(
                new DateFormatter(DateFormat.getDateInstance(DateFormat.MEDIUM))));
        //datePicker = new DatePicker();
        dateField.setBorder(null);
        setBackground(dateField.getBackground());
    }
    
    public DatePicker getDatePicker() {
        return datePicker;
    }

    public void setDatePicker(DatePicker datePicker) {
        this.datePicker = datePicker;
    }

    public Object getValue() {
        return dateField.getValue();
    }
    public void setValue(Object value) {
        this.dateField.setValue(value);
    }
    
    public DateTextField getDateField() {
        return dateField;
    }

    public void setDateField(DateTextField dateField) {
        this.dateField = dateField;
    }


    public JButton getDateButton() {
        return dateButton;
    }

    public void setDateButton(JButton dateButton) {
        this.dateButton = dateButton;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateButton = new javax.swing.JButton();
        dateField = new com.vns.comp.DateTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);

        dateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vns/comp/calendar.gif"))); // NOI18N
        dateButton.setToolTipText("Popup Calendar");
        dateButton.setBorder(null);
        dateButton.setBorderPainted(false);
        dateButton.setContentAreaFilled(false);
        dateButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        dateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateButtonActionPerformed(evt);
            }
        });

        dateField.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(dateField, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(dateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
            .addComponent(dateField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateButtonActionPerformed
        //datePicker = new DatePicker(dateField);
        datePicker.start(this);
    }//GEN-LAST:event_dateButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dateButton;
    private com.vns.comp.DateTextField dateField;
    // End of variables declaration//GEN-END:variables
}
